n = get_null()
nc = fill_<SubstituteBy:Boolean|int|float|string>_column(n, 10)
t = create_table([nc])
write_to_csv(t, 'test_output/test.csv')
same_content('test_output/test.csv', 'test_output/null10.csv')